// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Model.Data;

namespace Test.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Model.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BaseWeight")
                        .HasColumnType("float");

                    b.Property<double?>("BaseWeightLFace")
                        .HasColumnType("float");

                    b.Property<double?>("BaseWeightLMid")
                        .HasColumnType("float");

                    b.Property<string>("ProductBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TambId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TambId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("Test.Model.Tamb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("WeightDryAct")
                        .HasColumnType("float");

                    b.Property<double?>("WeightDryRef")
                        .HasColumnType("float");

                    b.Property<double?>("WeightMainAct")
                        .HasColumnType("float");

                    b.Property<double?>("WeightMainRef")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tambs");
                });

            modelBuilder.Entity("Test.Model.Lab", b =>
                {
                    b.HasOne("Test.Model.Tamb", "Tamb")
                        .WithMany("Lab")
                        .HasForeignKey("TambId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tamb");
                });

            modelBuilder.Entity("Test.Model.Tamb", b =>
                {
                    b.Navigation("Lab");
                });
#pragma warning restore 612, 618
        }
    }
}
